# Use the latest Ubuntu LTS release as the base image
FROM ubuntu:latest

RUN apt-get update
RUN apt-get install --yes software-properties-common
RUN add-apt-repository --yes --update ppa:ansible/ansible
RUN apt-get install --yes ansible
RUN apt-get install strace