---
- name: Modify user settings
  hosts: localhost
  tasks:
    - name: Ensure group "mygroup" exists
      ansible.builtin.group:
        name: mygroup
        state: present
        
    - name: Ensure a user exists and is in a specific group
      ansible.builtin.user:
        name: myuser
        group: mygroup
        state: present

    # - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
    #   ansible.builtin.file:
    #     path: /etc/foo.conf
    #     state: touch
    #     mode: u=rw,g=r,o=r

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/foo
        state: directory
        mode: '0755'

    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: /etc/foo
        state: directory
        recurse: yes
        owner: myuser
        group: mygroup
