---
- name: Modify user settings
  hosts: localhost
  tasks:
    - name: Ensure group "mygroup" exists
      ansible.builtin.group:
        name: mygroup
        state: present
        
    - name: Ensure a user exists and is in a specific group
      ansible.builtin.user:
        name: myuser
        group: mygroup
        state: present

    - name: Change folder ownership and group
      ansible.builtin.file:
        path: /etc/foo
        state: directory
        recurse: yes
        owner: myuser
        group: mygroup
        mode: u=rw,g=r,o=r
